name: NASA Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repo
      - uses: actions/checkout@v3

      # 2) Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3) Install root dependencies
      - name: Install root dependencies
        run: npm install

      # 4) Install client dependencies
      - name: Install client dependencies
        run: npm install --prefix client

      # 5) Install server dependencies
      - name: Install server dependencies
        run: npm install --prefix server

      # 6) Build the client
      - name: Build client
        run: npm run build --prefix client

      # 7) Run client tests
      - name: Test client
        run: npm test --prefix client

      # 8) Run server tests
      - name: Test server
        run: npm test --prefix server
