name: NASA Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env: 
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      # Check out your code
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Build client
        run: npm run build --prefix client

      - name: Test Client + Server
        run: npm test
